---
version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Create version.json
          command: |
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" > version.json
      - setup_remote_docker
      - run:
          name: Build
          command: |
            ls
            pwd
            docker info
            docker build -t app:build .
      - run:
          name: Test
          command: /bin/echo "No tests"
      - run:
          name: Push
          command: |
            cat << EOF
            CIRCLE_PROJECT_REPONAME : ${CIRCLE_PROJECT_REPONAME}
            CIRCLE_TAG : ${CIRCLE_TAG}
            CIRCLE_BRANCH : ${CIRCLE_BRANCH}
            DOCKER_IMAGE : ${DOCKER_IMAGE}
            EOF
            export DOCKER_IMAGE="mozilla/${CIRCLE_PROJECT_REPONAME}:latest"
            if [ -n "${CIRCLE_TAG}" ]; then
              export DOCKER_IMAGE="mozilla/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}"
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ] || [ -n "${CIRCLE_TAG}" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag app:build "${DOCKER_IMAGE}"
              docker push "${DOCKER_IMAGE}"
            fi
      - store_artifacts:
          path: version.json
workflows:
  version: 2
  untagged-build:
    jobs:
      - build
